version: "3.9"
services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: money
            POSTGRES_PASSWORD: STy6KEnk

    flyway:
        image: flyway/flyway
        command: -url=jdbc:postgresql://db:5432/money -user=postgres -password=STy6KEnk -connectRetries=60 migrate
        volumes:
            - ./sql:/flyway/sql
        depends_on:
            - db